Repository theforeman/smart_proxy_remote_execution_ssh, pull requests merged in 2020-05, with the labels that each got.

#46 Allow newer bundler versions
  smart_proxy_remote_execution_ssh.gemspec
Labels: Needs testing, Waiting on contributor

#48 Rubocop 0.80
  .rubocop.yml
  .rubocop_todo.yml
  lib/smart_proxy_remote_execution_ssh/cockpit.rb
Labels: Needs testing, Not yet reviewed

#49 Unpin dependencies
  .rubocop_todo.yml
  Gemfile
  smart_proxy_remote_execution_ssh.gemspec
Labels: Needs testing
