Repository theforeman/smart_proxy_remote_execution_ssh, pull requests merged in 2021-06, with the labels that each got.

#52 Fixes #32543 - Import foreman_remote_execution_core
  lib/smart_proxy_remote_execution_ssh.rb
  lib/smart_proxy_remote_execution_ssh/actions/run_script.rb
  lib/smart_proxy_remote_execution_ssh/async_scripts/control.sh
  lib/smart_proxy_remote_execution_ssh/async_scripts/retrieve.sh
  lib/smart_proxy_remote_execution_ssh/dispatcher.rb
  lib/smart_proxy_remote_execution_ssh/log_filter.rb
  lib/smart_proxy_remote_execution_ssh/plugin.rb
  lib/smart_proxy_remote_execution_ssh/runners.rb
  lib/smart_proxy_remote_execution_ssh/runners/fake_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/polling_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
  settings.d/remote_execution_ssh.yml.example
  smart_proxy_remote_execution_ssh.gemspec
  test/api_test.rb
  test/test_helper.rb
Labels: Needs testing

#53 Fixes #31516 - Make cockpit work with passphrase
  lib/smart_proxy_remote_execution_ssh/cockpit.rb
Labels: Needs testing, Not yet reviewed

#54 Fixes #32774 - use directly smart_proxy_dynflow
  lib/smart_proxy_remote_execution_ssh.rb
  lib/smart_proxy_remote_execution_ssh/actions/run_script.rb
  lib/smart_proxy_remote_execution_ssh/dispatcher.rb
  lib/smart_proxy_remote_execution_ssh/plugin.rb
  lib/smart_proxy_remote_execution_ssh/runners/fake_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/polling_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
  smart_proxy_remote_execution_ssh.gemspec
Labels: Needs testing, Not yet reviewed

#56 Refs #32774 - use SmartProxyDynflow
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
Labels: Needs testing, Not yet reviewed

#44 Update to bundler.d to match other smart proxy plugins
  bundler.d/remote_execution_ssh.rb
  bundler.plugins.d/foreman_remote_execution_core.rb
  smart_proxy_remote_execution_ssh.gemspec
Labels: Needs testing, Waiting on contributor
