Repository theforeman/smart_proxy_remote_execution_ssh, pull requests merged in 2022-03, with the labels that each got.

#55 Fixes #30277 - Allow spaces in remote_working_dir
  lib/smart_proxy_remote_execution_ssh/runners/polling_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
Labels: Needs testing

#71 Fixes #34378 - Use process abstractions from sp-dynflow
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
Labels: Needs testing

#72 Fixes #34363 - Improve error reporting
  lib/smart_proxy_remote_execution_ssh/runners/polling_script_runner.rb
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
Labels: Needs testing, Waiting on contributor

#66 Fixes #33759 - Deliver cancellation notifications to clients
  lib/smart_proxy_remote_execution_ssh/actions/pull_script.rb
Labels: Needs testing, Waiting on dependencies

#76 Refs #34378 - Bump sp-dynflow dependency
  smart_proxy_remote_execution_ssh.gemspec
Labels: Needs testing
