Repository theforeman/smart_proxy_remote_execution_ssh, pull requests merged in 2022-05, with the labels that each got.

#74 Fixes #34595 - Control socket path length
  lib/smart_proxy_remote_execution_ssh.rb
  lib/smart_proxy_remote_execution_ssh/plugin.rb
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
  settings.d/remote_execution_ssh.yml.example
Labels: Needs testing

#83 Fixes #34869 - Suppress messages about shared connection being closed
  lib/smart_proxy_remote_execution_ssh/runners/script_runner.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#80 Fixes #34828 - Strip CR from script before passing it to pull provider
  lib/smart_proxy_remote_execution_ssh/actions/pull_script.rb
Labels: Needs testing, Waiting on contributor

#78 Refs #34667 - Fall back to server set of certs
  lib/smart_proxy_remote_execution_ssh.rb
  lib/smart_proxy_remote_execution_ssh/actions/pull_script.rb
Labels: Needs testing, Not yet reviewed
